# Generated by `mcc completions emit` from the argparse parser.
# DO NOT EDIT BY HAND — run `mcc completions emit` to regenerate.

_mcc_complete() {
    COMPREPLY=()
    local cur cword words prev IFS=$' \t\n'
    cur="${COMP_WORDS[COMP_CWORD]}"
    cword=$COMP_CWORD
    words=("${COMP_WORDS[@]}")
    prev=""
    (( cword > 0 )) && prev="${words[$((cword-1))]}"

    # ---- Top level: subcommands ∪ registered session names ----
    if (( cword == 1 )); then
        local subs="completions create disable enable list migrate reflect session setup status switch team update version vscode help"
        local sessions
        sessions=$(mcc complete --kind session 2>/dev/null)
        COMPREPLY=( $(compgen -W "${subs} ${sessions}" -- "${cur}") )
        return
    fi

    local cmd1="${words[1]}"
    local cmd2=""
    local args_start=2

    # ---- Two-level nouns ----
    case "$cmd1" in
        completions)
            if (( cword == 2 )); then
                COMPREPLY=( $(compgen -W "bash emit install print uninstall verify zsh" -- "$cur") )
                return
            fi
            cmd2="${words[2]}"
            args_start=3
            ;;
        reflect)
            if (( cword == 2 )); then
                COMPREPLY=( $(compgen -W "list scan submit" -- "$cur") )
                return
            fi
            cmd2="${words[2]}"
            args_start=3
            ;;
        session)
            if (( cword == 2 )); then
                COMPREPLY=( $(compgen -W "list resume set transcript" -- "$cur") )
                return
            fi
            cmd2="${words[2]}"
            args_start=3
            ;;
        team)
            if (( cword == 2 )); then
                COMPREPLY=( $(compgen -W "setup status" -- "$cur") )
                return
            fi
            cmd2="${words[2]}"
            args_start=3
            ;;
    esac

    # ---- Special case: --group <label>=<csv-of-sessions> ----
    if [[ "$prev" == "--group" && "$cur" == *=* ]]; then
        local label="${cur%%=*}"
        local list="${cur#*=}"
        local last="${list##*,}"
        local prefix=""
        [[ "$list" == *,* ]] && prefix="${list%,*}"
        local sessions s
        sessions=$(mcc complete --kind session 2>/dev/null)
        COMPREPLY=()
        for s in $sessions; do
            [[ "$s" == "$last"* ]] || continue
            if [[ -n "$prefix" ]]; then
                COMPREPLY+=( "${label}=${prefix},${s}" )
            else
                COMPREPLY+=( "${label}=${s}" )
            fi
        done
        return
    fi

    # ---- Flag-with-value: complete the value ----
    case "$prev" in
        --output|--rc-file)
            compopt -o default 2>/dev/null
            COMPREPLY=()
            return ;;
        --group-by)
            COMPREPLY=( $(compgen -W "scope none custom" -- "$cur") )
            return ;;
        --group)
            return ;;
        --persona)
            local items
            items=$(mcc complete --kind persona 2>/dev/null)
            COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            return ;;
        --plugin)
            COMPREPLY=( $(compgen -W "pdt mam mama bus" -- "$cur") )
            return ;;
        --scope)
            local items
            items=$(mcc complete --kind scope 2>/dev/null)
            COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            return ;;
        --shell)
            COMPREPLY=( $(compgen -W "bash zsh" -- "$cur") )
            return ;;
        --kind|--name|--repo)
            return ;;
    esac

    # ---- Bare flag completion (cur starts with -) ----
    if [[ "$cur" == -* ]]; then
        local flags=""
        case "$cmd1:$cmd2" in
            complete:)  flags="--kind" ;;
            completions:emit)  flags="--output" ;;
            completions:install)  flags="--rc-file --shell" ;;
            completions:print)  flags="--shell" ;;
            completions:uninstall)  flags="--rc-file --shell" ;;
            create:)  flags="--persona --plugin --scope" ;;
            reflect:submit)  flags="--no-confirm --no-scan --repo" ;;
            session:list)  flags="--all --paths --show-path" ;;
            session:set)  flags="--scope" ;;
            session:transcript)  flags="--chronological --include-compact-summaries --include-harness-commands --include-meta --include-thinking --live-branch --output --post-compact-only" ;;
            team:setup)  flags="--name" ;;
            vscode:)  flags="--group --group-by --no-folder-open" ;;
        esac
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return
    fi

    # ---- Count positional args consumed (skipping flags + their values) ----
    local pos_idx=0 i w
    for ((i=args_start; i<cword; i++)); do
        w="${words[$i]}"
        case "$w" in
            --group|--group-by|--kind|--name|--output|--persona|--plugin|--rc-file|--repo|--scope|--shell)
                ((i++)) ;;
            --*)
                ;;
            *)
                ((pos_idx++)) ;;
        esac
    done

    # ---- Positional completion ----
    case "$cmd1:$cmd2" in
        create:)
            (( pos_idx == 0 )) && {
                local items
                items=$(mcc complete --kind session 2>/dev/null)
                COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            }
            return ;;
        disable:)
            (( pos_idx == 0 )) && COMPREPLY=( $(compgen -W "pdt mam mama bus" -- "$cur") )
            return ;;
        enable:)
            (( pos_idx == 0 )) && COMPREPLY=( $(compgen -W "pdt mam mama bus" -- "$cur") )
            return ;;
        reflect:scan)
            (( pos_idx == 0 )) && compopt -o default 2>/dev/null
            (( pos_idx == 0 )) && COMPREPLY=()
            return ;;
        reflect:submit)
            (( pos_idx == 0 )) && compopt -o default 2>/dev/null
            (( pos_idx == 0 )) && COMPREPLY=()
            return ;;
        session:resume)
            (( pos_idx == 0 )) && {
                local items
                items=$(mcc complete --kind session 2>/dev/null)
                COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            }
            return ;;
        session:set)
            {
                local items
                items=$(mcc complete --kind session 2>/dev/null)
                COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            }
            return ;;
        session:transcript)
            (( pos_idx == 0 )) && {
                local items
                items=$(mcc complete --kind session 2>/dev/null)
                COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            }
            return ;;
        switch:)
            (( pos_idx == 0 )) && COMPREPLY=( $(compgen -W "mam mama off" -- "$cur") )
            return ;;
        vscode:)
            {
                local items
                items=$(mcc complete --kind session_or_scope_or_all 2>/dev/null)
                COMPREPLY=( $(compgen -W "$items" -- "$cur") )
            }
            return ;;
    esac
}
complete -F _mcc_complete mcc
